server:
  port: 8081

card:
  days_to_close_card: 7

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maney
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl:
          auto: update
  sql:
    init:
      password:

