server:
  port: 8080

card:
  days_to_close_card: 7

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maney
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl:
          auto: update
  sql:
    init:
      password:

security:
  key: 6A586E3272357538782F413F4428472B4B6150645367566B5970337336763979